### ISSUE TITLE
Undeclared dependency on Dist::Iller::Standard

### ISSUE THREAD

**Issue by andk** [Csson/p5-Dist-Iller-Config-Author-CSSON#1]
As per subject. Grep:

http://search.cpan.org/grep?release=Dist-Iller-Config-Author-CSSON-0.0100;string=Dist::Iller::Standard;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/62547846

HTH&&Thanks,

**Comment by Csson** [comment]
Hi!

I _think_ this is fixed in 0.0101 (just released). I'll keep the issue open until a few tests are reported.

/Erik
